// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4ZSOWDtMuzDFWpibUJU1p-G_CBE8Bo4',
    appId: '1:913563579711:web:7c12e11225328b24d84f8a',
    messagingSenderId: '913563579711',
    projectId: 'music-app-project-17632',
    authDomain: 'music-app-project-17632.firebaseapp.com',
    storageBucket: 'music-app-project-17632.firebasestorage.app',
    measurementId: 'G-5VBQGVFTXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxU1irVDwZ_Pi0JlIwpPtqiZ4WyQsQSl8',
    appId: '1:913563579711:android:c9ed6fba86ca88c0d84f8a',
    messagingSenderId: '913563579711',
    projectId: 'music-app-project-17632',
    storageBucket: 'music-app-project-17632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEX02woqAGhJzsg9wCJpEGlaXgnx3ifx0',
    appId: '1:913563579711:ios:1c344a5d02c2b995d84f8a',
    messagingSenderId: '913563579711',
    projectId: 'music-app-project-17632',
    storageBucket: 'music-app-project-17632.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEX02woqAGhJzsg9wCJpEGlaXgnx3ifx0',
    appId: '1:913563579711:ios:1c344a5d02c2b995d84f8a',
    messagingSenderId: '913563579711',
    projectId: 'music-app-project-17632',
    storageBucket: 'music-app-project-17632.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa4ZSOWDtMuzDFWpibUJU1p-G_CBE8Bo4',
    appId: '1:913563579711:web:d91f5fe0813bb998d84f8a',
    messagingSenderId: '913563579711',
    projectId: 'music-app-project-17632',
    authDomain: 'music-app-project-17632.firebaseapp.com',
    storageBucket: 'music-app-project-17632.firebasestorage.app',
    measurementId: 'G-XG1RF37QYJ',
  );

}